"""wallet_model

Revision ID: a7bf8c15589f
Revises:
Create Date: 2025-07-11 12:43:24.272551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7bf8c15589f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False, comment='Wallet ID'),
                    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False,
                              server_default='0.00', comment='Wallet balance'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation date'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    # ### end Alembic commands ###
